
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	enrichmentChamber = "120000"
	#Base energy storage (Joules).
	osmiumCompressor = "480000"
	#Base energy storage (Joules).
	combiner = "240000"
	#Base energy storage (Joules).
	crusher = "120000"
	#Base energy storage (Joules).
	metallurgicInfuser = "120000"
	#Base energy storage (Joules).
	purificationChamber = "480000"
	#Base energy storage (Joules).
	energizedSmelter = "120000"
	#Base energy storage (Joules).
	digitalMiner = "240000"
	#Base energy storage (Joules).
	electricPump = "240000"
	#Base energy storage (Joules).
	chargePad = "3072000"
	#Base energy storage (Joules).
	rotaryCondensentrator = "120000"
	#Base energy storage (Joules).
	oxidationChamber = "480000"
	#Base energy storage (Joules).
	chemicalInfuser = "480000"
	#Base energy storage (Joules).
	chemicalInjectionChamber = "960000"
	#Base energy storage (Joules).
	electrolyticSeparator = "960000"
	#Base energy storage (Joules).
	precisionSawmill = "120000"
	#Base energy storage (Joules).
	chemicalDissolutionChamber = "960000"
	#Base energy storage (Joules).
	chemicalWasher = "480000"
	#Base energy storage (Joules).
	chemicalCrystallizer = "960000"
	#Base energy storage (Joules).
	seismicVibrator = "120000"
	#Base energy storage (Joules).
	pressurizedReactionBase = "12000"
	#Base energy storage (Joules).
	fluidicPlenisher = "240000"
	#Base energy storage (Joules).
	laser = "12000000"
	#Base energy storage (Joules).
	formulaicAssemblicator = "240000"
	#Base energy storage (Joules).
	teleporter = "30000000"
	#Base energy storage (Joules).
	modificationStation = "240000"
	#Base energy storage (Joules).
	isotopicCentrifuge = "480000"
	#Base energy storage (Joules).
	nutritionalLiquifier = "240000"
	#Base energy storage (Joules). Also defines max process rate.
	antiprotonicNucleosynthesizer = "6000000000"
	#Base energy storage (Joules).
	pigmentExtractor = "240000"
	#Base energy storage (Joules).
	pigmentMixer = "480000"
	#Base energy storage (Joules).
	paintingMachine = "240000"
	#Base energy storage (Joules). Also defines max output rate.
	spsPort = "6000000000"

